version: '2'

services:
  redis:
    image: redis
    restart: always
    volumes:
        - $HOME/data/redis:/data
    command:  redis-server --appendonly yes
  api:
    build: .
    ports:
      - "8876:8876"
    volumes:
      - ../pubpatterns:/var/lib/pubpatterns
    links:
      - redis
    restart: always
